service: morgentalmtc-curso-sls
provider:
  name: aws
  runtime: nodejs10.x
  credentials: ${file(./.env.yml):credentials}
custom:
  writeEnvVars:
    ENDPOINT: ${file(./.env.yml):${opt:stage}.ENDPOINT}
    TOKEN: ${file(./.env.yml):${opt:stage}.TOKEN}
    EMAIL: ${file(./.env.yml):${opt:stage}.EMAIL}
    MAILCHIMP: ${file(./.env.yml):${opt:stage}.MAILCHIMP}
    LISTID: ${file(./.env.yml):${opt:stage}.LISTID}
    SANDBOX: ${file(./.env.yml):${opt:stage}.SANDBOX}
    SANDBOX_EMAIL: ${file(./.env.yml):${opt:stage}.SANDBOX_EMAIL}
    NOTIFICATIONEMAIL: ${file(./.env.yml):${opt:stage}.NOTIFICATIONEMAIL}

plugins:
  - serverless-plugin-write-env-vars
functions:
  api:
    handler: index.main
    events:
      - http: ANY {proxy+}
        cors: true
