service: joelvardy-v1

custom:
  stage: ${opt:stage, self:provider.stage}
  service: ${self:service}-${self:custom.stage}

provider:
  name: aws
  region: eu-west-1

resources:
  - ${file(resources/s3.yml)}
  - ${file(resources/cf.yml)}
  - ${file(resources/r53.yml)}
