# Name of your Serverless service
service: serverless-dynamodb-rest-poc

# Serverless framework (You can leaves this alone)
frameworkVersion: ">=1.1.0 <2.0.0"

#app: my-serverless-app # App name used to publish your service to the serverless platform
#tenant: user # User used to publish your service to the serverless platform

# Serverless plugins
plugins:
  - serverless-dynamodb-local
  - serverless-offline

# Custom variables (Used by plugins and in this doc)
custom:

  # DynamoDB Local Settings
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
    stages:
      - dev

  # Serverless Offline Settings
  serverless-offline:
    port: 3000
    prefix: ${self:provider.environment.REST_PATH_PREFIX} # Adds a prefix to every path, to send your requests to http://localhost:3000/[prefix]/[your_path] instead
#    httpsProtocol: "resources/dev-certs" # To enable HTTPS, specify directory (relative to your cwd, typically your project dir) for both cert.pem and key.pem files.

# Serverless provider settings
provider:
  name: aws
  runtime: nodejs4.3
  environment:
    REST_PATH_PREFIX: v1
    TODOS_TABLE: todo-${opt:stage, self:provider.stage}
  iamRoleStatements: ${file(resources/iam-role-stmt-resources.yml)}

# Serverless functions
functions: ${file(resources/root-functions.yml)}

# Serverless resources (See resources/dynamodb-tables.yml)
resources:
  - ${file(resources/dynamodb-tables.yml)}
