service: slack-driver
plugins:
  - serverless-python-requirements
custom:
  stage: ${env:STAGE}
  pythonRequirements:
    dockerizePip: false
    dockerImage: mozillaiam/docker-sls:latest
    cleanupZipHelper: true
provider:
  name: aws
  runtime: python3.6
  stage: ${env:STAGE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:DescribeStream"
        - "dynamodb:GetItem"
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:ListStreams"
        - "dynamodb:ListTables"
        - "dynamodb:ListTagsOfResource"
        - "dynamodb:Query"
        - "dynamodb:Scan"
      Resource: arn:aws:dynamodb:*:*:table/${file(${self:custom.stage}-vars.yml):CIS_DYNAMODB_PERSON_TABLE}
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:GetItem"
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:ListStreams"
        - "dynamodb:ListTables"
        - "dynamodb:ListTagsOfResource"
        - "dynamodb:Query"
        - "dynamodb:Scan"
      Resource: arn:aws:dynamodb:*:*:table/credential-store
# To be used to store deactivated users, so that they can be deleted later on automatically, after a grace period
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:GetItem"
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:ListStreams"
        - "dynamodb:ListTables"
        - "dynamodb:ListTagsOfResource"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
      Resource: arn:aws:dynamodb:*:*:table/slack-driver-state
    -
      Effect: "Allow"
      Action:
        - "logs:*"
      Resource:
        - "arn:aws:logs:*:*:log-group:/cis/**"
functions:
  slack-driver:
    handler: driver.handle
    timeout: 300
    environment: ${file(${self:custom.stage}-vars.yml)}
    events:
      - schedule:
          name: slack-driver-5-minute-sync
          description: 'Sync active users with Slack every 5 minutes'
          rate: rate(5 minutes)
          enabled: true
resources:
  Resources:
    stateTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: slack-driver-state
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
