service: cdm

provider:
  name: aws
  # The AWS region in which to deploy (us-east-1 is the default)
  region: us-west-2
  # The stage of the application, e.g. dev, production, stagingâ€¦ ('dev' is the default)
  stage: dev
  runtime: provided
  vpc:
    securityGroupIds:
      - sg-036f5cdc0ca84ff88
    subnetIds:
      - subnet-083d31b93d87a77f6
      - subnet-0ee565742c26c9143
  environment:
    DB_HOST: ${env:MYSQL_HOST}
    DB_DATABASE: ${env:MYSQL_DATABASE}
    DB_USERNAME: ${env:MYSQL_USERNAME}
    DB_PASSWORD: ${env:MYSQL_PASSWORD}
    azureClientID: api://1039b1ea-694d-48f0-bc67-90c533b3b570
    azureClientSecret: ${env:AZURECLIENTSECRET}
    azureRedirectUri: localhost:5000
    twilio_scheduling_number: "+19718035717"
    twilio_job_details_number: "+19713512367"
    twilio_bulk_number: "+15035064689"
    TWILIO_SID: ${env:TWILIO_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_KEY}
    SPECIAL_ENDPOINT_URL: https://flzbu88cxj.execute-api.us-west-2.amazonaws.com/dev
package:
  # Directories to exclude from deployment
  exclude:
    - node_modules/**
    - public/storage
    - resources/assets/**
    - storage/**
    - tests/**

functions:
  # This function runs the Laravel website/API
  web:
    handler: public/index.php
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      - http: "ANY /"
      - http: "ANY /{proxy+}"
  # This function lets us run artisan commands in Lambda
  artisan:
    handler: artisan
    timeout: 120 # in seconds
    layers:
      - ${bref:layer.php-74} # PHP
      - ${bref:layer.console} # The "console" layer

plugins:
  # We need to include the Bref plugin
  - ./vendor/bref/bref
