
service: deploy-test-two

provider:
  name: aws
  runtime: nodejs12.x
  stage : dev
  region: ap-south-1
  role: arn:aws:iam::667505010803:role/wss-lambda-execute
  timeout: 10

plugins:
  - serverless-offline

functions:
  api:
    handler: index.execute
    events:
     - http:
         path: /{proxy+}
         method: ANY
         cors: true
