service: forex-jbfonacierquiz

frameworkVersion: "<=1.26.0"

custom:
  namespace: ${self:service}-${self:custom.stage}
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: ap-southeast-1
  environment:
    CLIENT_ID: '306696921751.321308399271'
    CLIENT_SECRET: b7babca878339857d07c916293e61adc
    VERIFICATION_TOKEN: coCnB10lfPXATjlGVQj4lo5n
    INSTALL_ERROR_URL: http://serverlessslackbot.s3-website-us-east-1.amazonaws.com/#error
    INSTALL_SUCCESS_URL: http://forex-jbfonacierquiz.s3-website-ap-southeast-1.amazonaws.com
    NAMESPACE: ${self:custom.namespace}
    TEAMS_TABLE: ${self:custom.namespace}-teams
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:*:*:table/${self:provider.environment.TEAMS_TABLE}

functions:
  events:
    handler: events.handler
    events:
      - http:
          path: events
          method: post
  install:
    handler: install.handler
    events:
      - http:
          path: install
          method: get

resources:
  Resources:
    TeamsDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TEAMS_TABLE}
        AttributeDefinitions:
          - AttributeName: team_id
            AttributeType: S
        KeySchema:
          - AttributeName: team_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
