# -*- coding: utf-8 -*-
# all available properties in serverless.yml when provider is aws
# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service:
  name: jenkins-playground

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  profile: eq_sanhe
  memorySize: 128
  timeout: 3
  deploymentBucket:
    name: eq-sanhe
  deploymentPrefix: serverless
  role: arn:aws:iam::{AWS_ACCOUNT_ID}:role/cookiecutter-pygitrepo-test # CHANGE THIS
  versionFunctions: false
  environment:
    # Inject non-sensitive config into lambda runtime environment variable.
    # for sensitive config, use secret manager.
    PYGITREPO_PROJECT_NAME: ${file(./config/config-final-for-serverless.json):PROJECT_NAME}

package:
  artifact: ./build/lambda/source.zip

functions:
  my_func:
    handler: jenkins_playground.handlers.my_func.handler
    description:
    layers:
      - "arn:aws:lambda:us-east-1:{AWS_ACCOUNT_ID}:layer:jenkins_playground:1" # CHANGE THIS
