service: lambda-nestjs

frameworkVersion: '2'

plugins:
  - serverless-layers

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  deploymentBucket: nekohack-lambda-nestjs
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

package:
  individually: true
  include:
    - dist/**
  exclude:
    - "**"

functions:
  index:
    handler: dist/lambda.handler
    events:
      - http:
          cors: true
          path: "/"
          method: any
      - http:
          cors: true
          path: "{proxy+}"
          method: any
