service: gss

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  environment:
    DYNAMODB_TABLE: gss
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/sk-pk-index"
functions:
  createCustomer:
    handler: backend/customers.create
    events:
      - http:
          path: /customer
          method: post
          cors: true
  getCustomer:
    handler: backend/customers.get
    events:
      - http:
          path: /customer/{id}
          method: get
          cors: true
  createSurvey:
    handler: backend/surveys.create
    events:
      - http:
          path: /survey
          method: post
          cors: true
          request:
            schema:
              application/json: ${file(backend/models/surveySchema.json)}
  getSurvey:
    handler: backend/surveys.get
    events:
      - http:
          path: /survey/{id}
          method: get
          cors: true
  getAllCustomerSurveys:
    handler: backend/surveys.get_all
    events:
      - http:
          path: /customer/{id}/surveys
          method: get
          cors: true
  createResponse:
    handler: backend/responses.create
    events:
      - http:
          path: /response
          method: post
          cors: true
          request:
            schema:
              application/json: ${file(backend/models/responseSchema.json)}
  getResponse:
    handler: backend/responses.get
    events:
      - http:
          path: /response/{id}
          method: get
          cors: true
  getAllResponses:
    handler: backend/responses.get_all
    events:
      - http:
          path: /survey/{id}/responses
          method: get
          cors: true
