service: news-service

plugins:
  - serverless-offline
  - serverless-dotenv-plugin # use .env for environment vars

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage} # set the stage based on what Circle Branch is deploying
  region: eu-west-2 # default is us-east-1
  cfLogs: true
  # apiKeys:
  #   - news_api

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors: true
  fetchArticles:
    handler: handler.fetchArticles
    events:
      - http:
          path: /articles
          method: post
          # private: true
          cors: true
          request:
            parameters:
              querystrings:
                type: true
            schema:
              application/json: ${file(body_schemas/fetch.json)}
