service: trigger-dynamodb
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMODB_TABLE: Heroes
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

resources:
  Resources:
    HeroesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1 # Como Ã© um ambiente de estudos, pode ser baixo
          WriteCapacityUnits: 1

functions:
  hero-insert:
    handler: handler.heroesInsert
    events:
      - http:
          path: heroes
          method: post
          cors: true
